### PR TITLE
Remove json-server from hosts

### PR DESCRIPTION
**Pull request by yak80**
In yarn configuration we have:
```
    "build:client": "cross-env CLIENT_API_URL=http://localhost:3000 webpack --config webpack/client.config.js",
    "build:server": "cross-env SERVER_API_URL=http://json-server:3000 webpack --config webpack/server.config.js",
```
We must use different env vars for different cases(dev, ci, production)  
1. **[dev]** If server starts not from docker container(direct from cli `node server.js`) then `json-server` url is unknown and must be placed to `localhost`(or add `json-server` to `hosts`).
2. **[ci]** In fully dockenized environment(for example build into travisCI) localhost not accessible from container and must be used `json-server` in  CLIENT_API_URL.
3. **[production]** In this case instead `json-server` in CLIENT_API_URL must be used real dns address(like vue-app-example.dev).

### CODE REVIEW

**Comment by yak80** [comment]
@romandragan, may be  better use `json-server`  by default for both env variables? In other case on travisCI build we receive errors on tests.

**Comment by romandrahan** [comment]
>1. [dev] If server starts not from docker container(direct from cli node server.js) then json-server url is unknown and must be placed to localhost(or add json-server to hosts).

This behaviour is our concern. Especially for cases like those we cover all commands behind Yarn scripts.

> 2. [ci] In fully dockenized environment(for example build into travisCI) localhost not accessible from container and must be used json-server in CLIENT_API_URL.

Looks like we need to pass it by environment variable? Can you discover this case more detailed?

> 3. [production] In this case instead json-server in CLIENT_API_URL must be used real dns address(like vue-app-example.dev).

In this case, I think we need to pass real server address also with environment variable, that will be already defined somewhere in the production server.

P.S. Looks like we need to close this PR first, and only then close #9

**Comment by yak80** [comment]
@romandragan, i think we no other way, we need use this environment vars. In different configurations we have different settings.
But we may use default settings(when application starts throw `yarn` and this vars is empty) and other settings from start throw docker containers.
i propose this:
1. Add to webpack configs default values (`CLIENT_API_URL`=`SERVER_API_URL`=`localhost`). When app will build locally throw yarn API will work correct. This is dev configuration.
2. To .env file add variables `CLIENT_API_URL=json-server` and `SERVER_API_URL=json-server`
3. Fix `build` command in `Makefile` for setup  environment vars with values from `.env` file. In this case with docker containers all must work fine(and `travisCI` too).
4. On `production` need only update CLIENT_API_URL to real domain name in `.env` file

**Comment by romandrahan** [comment]
@yak80, 👍 nice idea. But why do we need `.env` file? We can just rely on environment variables, that will be set directly in the `Makefile` (https://stackoverflow.com/questions/23843106/how-to-set-environment-variable-in-makefile). On production server this variables will be set by system administrator directly in the system.

**Comment by yak80** [comment]
@romandragan, yes, firstly i think same. In Makefile its will more easy, but we have special file `.env` for environment variables and logically better put this api-vars here. But in this case need some special code to load them into makefile. 
Also `Makefile` looks like internal project file and vars declared here looks like internal var, needed for correct project build. But this API-vars looks like external(describe external environment). 
Also other users will find this vars more easy(its like config) in .env

**Comment by romandrahan** [comment]
@yak80, the main problem with `.env` file is that it's not good to change source code when you upload it to the production server.

But, it's OK for that project, cause we don't plan to publish built Docker image to production server or something else. So, you can try to implement your idea in the way, you propose - will see what it will bring to us in the future. But for now - without production step.

**Comment by yak80** [comment]
@romandragan Ok

**Comment by yak80** [comment]
@romandragan, some e2e tests fail, but its ok, because they just fixed into #9

**Review by romandrahan — CHANGES_REQUESTED** [review]
@yak80, we can use API URL much more simpler.

For server bundle we can always use just `json-server` as the URL, because requests from `node-frontend` image to the `json-server` image will always go under Docker environment.

For client bundle (dev or production, don't matter) we can always use for example `api.vue-app-example.dev`. And move all other routing routine to the server settings. On development machine it could be `hosts` file or using `--add-host` or `--dns` flag for `docker run` command. On production machine it could be any system setting, or just `hosts` file or redirect to another external server or anything else, that we don't know and shouldn't care about.

In this case we are moving routing problems out of the application level - it's good practice.

Please, try to implement it this way.

**Comment by yak80** [comment]
@romandragan, some probs exists here:

1.  we can't add `api.vue-app-example.dev` to `/etc/hosts` throw docker or docker-compose. `--add-host`, `extra-hosts` , .. add host to container's `hosts` file. But code run in browser, and browser look `api.vue-app-example.dev` in local `hosts`. Here need think about solution. At now i see only one: add it manually in `hosts`.

2. > For server bundle we can always use just json-server as the URL, because requests from node-frontend image to the json-server image will always go under Docker environment.

I think situation when `json server` and `server.js` starts locally without docker are possible. Debugging SSR locally without containers more quick. 
But this is not big prob and developer may easy fix it(if needed) by add `json-server` in `hosts`

**Comment by romandrahan** [comment]
@yak80

1. This is normal behaviour. We just send requests to `api.vue-app-example.dev` and it's not our business, where this request goes after. So here we need to back adding that to the readme.

2. We user tries to start app in a "not normal" way, it's also not our business. So we must not cover this situations.

**Review by yak80 — COMMENTED** [review]
fixed

**Review by romandrahan — APPROVED** [review]

**Pull request merged**
